server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://120.27.145.73:3306/app_web_casper?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: 120.27.145.73
    port: 6379

  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    idle-timeout: 300000         # 5分钟
    connection-timeout: 30000    # 30秒
    max-lifetime: 1800000        # 30分钟，建议小于MySQL wait_timeout
    keepalive-time: 30000        # 30秒
# Swagger OpenAPI 配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

aes:
  secret: "2f8c7e1a4b5d6c9f0e3b7a2d1c4e6f8b"

superadmin:
  username: superadmin
  password: superadmin123 